### PR TITLE
Update orphanet.yaml

### PR DESCRIPTION
**Pull request by lwinfree**
this is for the datasets available upon request, which require a Data Transfer Agreement & a fee for industry

### CODE REVIEW

**Comment by lwinfree** [comment]
And this one @kltm? Let me know if you agree with scoring please :)

**Comment by kltm** [comment]
@lwinfree 
I think I may have a slightly different interpretation of the site; maybe you can check my reasoning on it. I'm going to go ahead and take everything they say at face value. Under the only legal link I found, they have: `We...apply [X] to all...parts of our databases.` To me, that is all-encompassing, so I would likely not ding them on A.2. You have D.1.2 violations listed twice? I'm assuming that should be an E.1.2 and will change it. I agree that there is no B violation, and the D and E violations. I'm a little stuck on C though, as we have no information available about what is on the other side of the contact wall. However, they have the following line in their data catalog: `One‐year license + monthly update on a private site at orpha.net`. I think I would give them the benefit of the doubt that their private site is like their public one and fairly easy to work with.

I'm also a little unsure about the sparql endpoint you have listed--my assumption was that was for the open-access data, not the "private" data.

**Comment by lwinfree** [comment]
Updating the score on the new repo. Yes I agree with your take on A. I think we give them a pass on C. Yes, the second D should have been E (oops!)

**Comment by kltm** [comment]
assuming on new tracker

**Pull request closed without merging**
